### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#1]
Issue #1 is reserved for our first release 🎉  

### Description

WIP

### Tasks

- [x] #1 Use Github to organize tasks
- [x] #20 Move Hyperformula code to `handsontable/hyperformula` 
- [ ] #7 Finish public API 
    - [ ] #36 Add support for custom languages
    - [ ] #36 Add support for cultures
    - [ ] #37 Add support for custom formulas
    - [ ] #2 Define formula and meta data format 
    - [ ] #24 Function helpers: normalize, validate
    - [ ] #24 Evaluate function from string
    - [x] #22 Address translation helpers `a1ToCoords`, `coordsToA1` 
    - [x] #19 Export static `version` and `buildDate` from package.json 
    - [ ] #18 Refactor CRUD operations to remove auto recalculate 
    - [ ] #18 Add manual recalculate method 
    - [ ] #18 Add batch operations support 
- [x] #13 Implement all required functions 
- [x] #14 Implement all external function 
- [ ] #38 Figure out how do we handle filtering and sorting
- [ ] #16 Full support for data types 
    - [x] #4 Number precision 
    - [x] #3 Date/Time support 
    - [ ] #5 True/False aliases 
    - [ ] #16 Array constant support
- [ ] Full support for references 
    - [ ] #12 Worksheet references 
    - [ ] #11 3D references 
- [ ] Support all operators
    - [ ] Arithmetic operators
    - [ ] Logical/Comparison operators
    - [ ] Text Concatenation operator
    - [ ] #15 Reference operators 
- [x] Clean up the development tools
    - [x] #23 Remove `CsvImporter` i `CsvExporter` and their dependancies
    - [x] #23 Hide or remove from the runtime `this.stats.measure`, `this.dependencyGraph.stats.start` i `this.dependencyGraph.stats.end`
- [x] Write documentation for the engine 
    - [ ] Better descriptions for generated TSDoc
    - [ ] How to guide for quick start and usage instructions
    - [ ] #8  Readme that is NPM ready 
- [ ] Create new plugin for Handsontable https://github.com/handsontable/handsontable/issues/6466
- [ ] #17 Create a kitchen sink demo to prove that integration works well 
- [x] #25 Check Hyperformula dependencies with FOSSA (https://fossa.com)

### Yet to be addressed

- Undo and redo
- Copy, cut, paste
- Merged cells
- Cell validation
- Error reporting
- Moving rows / columns
- Syntax highlight

### Browser support
| Browser Name         | Version |
|---------------------|---------|
| Firefox                      | 58         |
| Safari                        | 11          |
| Chrome                    | 64         |
| iOS Safari                 | 11.2       |
| Chrome for Android | 64        |
| IE                              | 11         |
| Edge                         | 16        |
| Android browser      | 62         |
| Firefox Android        | 57         |

Appendix 9
