### ISSUE TITLE
EPIC: Add the outstanding formulas from formula.js

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#150]
## EPIC

In order to replace the current formula plugin in Handsontable with the new engine, we'd need to add the lacking formulas. As of the 6th of February 2020, there are **247 functions** to be added across **10 categories**.

The complete formula reference is here:
https://docs.google.com/spreadsheets/d/1jMvfY5DzMxmTiUTZB-8wwtMaKB2OqWEWqi-Ku1FogZE/edit#gid=1120069524

List of supported formulas by Formula.js (source for the above list):
https://github.com/handsontable/formula-parser/blob/develop/src/supported-formulas.js

- [x] #152 Add Compatibility functions
- [x] #153 Add Date and Time functions
- [x] #154 Add Engineering functions
- [ ] #155 Add Financial functions
- [x] #156 Add Information functions
- [x] #157 Add Logical functions
- [x] #158 Add Lookup and Reference functions
- [x] #159 Add Text functions
- [ ] #160 Add Statistical functions
- [x] #161 Add Math and Trigonometry functions

**Comment by wojciechczerniak** [comment]
We're done with functions for now.
