### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#205]
### Description

We have to create and publish the documentation for this project.

### Epic

- [ ] #8 Readme
- [ ] #202 Review public API reference (#7)
- [ ] #149 Create developer documentation
    - [ ] Requirements:
        - [ ] node.js 
            - minimal version is 10
            - but... for full string comparison support, it has to be compiled with a special flag
            - so the recommended version is 13
        - [ ] supported browsers
            - GPU support for gpu.js (will it fallback to cpu if not supported?)
        - [ ] dependencies
    - [ ] Installation guide, CDN: UMD or NPM: ES/CommonJS/TypeScript
    - [ ] Release notes
    - [ ] LicenseKey guide (if needed)
    - [ ] Basic usage guide (buildFromArray, buildFromSheets, buildEmpty)
    - [ ] Data operations, setting data/formulas and retriving the results/formulas, replacing sheet
    - [ ] CRUD operations explained
    - [ ] Config options explained
        - [ ] Number type precision
    - [ ] Helpers
        - [ ] Function validation, normalization, calculation
        - [ ] Address translations
        - [ ] Cell helpers, hasValue, hasFormula, getType
        - [ ] Stats (if any)
    - [ ] Working with Events
    - [ ] Handling errors
- [ ] #149 Advanced developer documentation
    - [ ] Changing language, adding custom language, localizing errors and error messages
    - [ ] Adding custom formulas, adding translations for them
    - [ ] Working with multiple worksheets
    - [ ] Named expressions / variables
    - [ ] Structured references
    - [ ] "Clipboard" support
    - [ ] Batch operations and optimizing calculations
    - [ ] Supported data types: date, number, boolean (vs distinct logical), duration, null, undefined, EmptyValue
        - [ ] Configuring more date formats (with moment.js, date-fns, and others): https://github.com/you-dont-need/You-Dont-Need-Momentjs
        - [ ] Configuring number format, omiting leading zero in decimals
        - [ ] How we handle invalid data types
    - [ ] GPU support
    - [ ] Testing HF in your app
    - [ ] Integrations
        - [ ] Demo z TS
        - [ ] Demo z Vue
        - [ ] Demo z Angular
        - [ ] Demo z React
        - [ ] Demo z NodeJS
        - [ ] Demo with remote JSON import/export
- [ ] Create contributtor documentation
    - [ ] Explain how does the engine work: parser, grammar, interpreter, AST, graph, optimizations
    - [ ] #125 Generate syntax diagram for grammar
    - [ ] Contributting new language (language files + meta)
    - [ ] Contributting new function (function + language + meta)
    - [ ] Contributing.md + Code of conduct + CLA explained
    - [ ] Writing tests for HF
    - [ ] Bug reporting, feature requests
- [ ] Create syntax documentation
    - [ ] Explain what is ODFF and which ISO standard we follow
    - [ ] Current evaluator level (incomplete SGE), current limitations, function names, named expression names requirements
    - [ ] ODFF Variances, explain differences to other spreadsheet engines and how to use configuration to adjust them
        - [ ] `leapYear1900`
        - [ ] `nullDate`
        - [ ] Number type precision
        - [ ] Year 1583 support
    - [ ] Supported types (from end user perspective)
    - [ ] Arithmetic operators, explain order of precedence
    - [ ] Logical operators
    - [ ] Text operators
    - [ ] `%` operator
    - [ ] Case sensitivity
    - [ ] Whitespace
    - [ ] Wildecards support
    - [ ] Functions syntax, optional parameters, omiting parameters, volatile functions, matrix functions
    - [ ] Constant Arrays, Dynamic Arrays support
    - [ ] References: cell, range, sheet
    - [ ] Error and their types, cycle errors, error propagation
    - [ ] Create functions documentation
        - [ ] Supported functions
        - [ ] Functions docs should be a Markdown generated from metadata #2
        - [ ] Add functions description metadata #2 
- [ ] #228 Setup documentation engine
    - [ ] Setup `vue-press` or `docusaurus` for Markdown documentation
    - [ ] Setup documentation versioning (breaking change and major versions only, no bug fixes)
    - [ ] Generate API reference Markdown from TSDoc
    - [ ] Setup Docker container where we can host the documentation
    - [ ] Add a redirect from `handsontable.com/docs/hyperformula` to the HF docs
    - [ ] Add a commend to Slack DeployBot or create a Github Action for easy publish flow

**Comment by wojciechczerniak** [comment]
Documentation was prepared and published with the initial release. More or less close to the ideas above, but they are now outdated. If there are some further improvements that we can do, we should discuss them in dedicated issues.
