### ISSUE TITLE
[v1.x.0] Release

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#210]
### Description

Extracted features from #54 that are not necessary for the first release.

- [ ] #7 API
    - [ ] #126 Named Expressions and Structure References (split into smaller tasks)
    - [ ] #131 Support constant array / dynamic array types
    - [ ] #117 We can't update the config after initialization
    - [ ] #221 A few more functions for the initial release
    - [ ] #220 Wildcards support
