### ISSUE TITLE
Named Expressions: API and structure (aka Stage 1)

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#239]
### Description

This is a part of the #126 Named Expressions Epic.

#### Goals

- [x] Create an internal structure that is necessary to implement #24 and #126 
- [x] Have an API for #126 done as the first stage of larger functionality

#### Types
Without tables/arrays:

- [x] Defined names:
    - [x] Reference. If the expression does start with equality sign: range =A1:C30 or cell =A1
    - [x] Formula. If the reference contains the formula: =SUM(A1:A5)
    - [x] Constant. If reference is just a value: 3, "some string", 10/12/2020
- [ ] ~Defined table. If the expression does not start with equality sign: E1:G26 it is a table where the first row is a header and the last row is a total.~ Arrays are not supported yet #131 

#### API
Without `scope` and `options`. The only `scope` that is supported at this stage is the global one.

`options = { comment, visibility }`

- [x] `engine.addNamedExpression(name, value, scope, options)`
- [x] `engine.removeNamedExpression(name, scope)`
- [x] `engine.changeNamedExpression(name, newValue, newScope, newOptions)`
- [x] `engine.getNamedExpressionValue(name, scope)`
- [ ] `engine.getNamedExpressionFormula(name, scope)`
- [x] `engine.listNamedExpressions(scope?)` 

#### Naming rules

- [x] Up to 255 characters length.
- [x] Names can contain large and small letters but matching is case insensitive. The evaluator engine should normalize the name. The registered name should be used when stringifying AST.
- [x] Names that look like a cell reference are not allowed. A1: `$A$100`, or R1C1.
- [x] The first character should be a letter or an underscore. The rest can contain letters, numbers, periods and underscores.
- [x] Whitespace is not allowed in named expression. It is allowed inside structured references enclosed in square brackets `[ ]` and should be preserved to improve readability.
- [ ] ~Some characters have special meaning for syntax: `[`, `]`, `#` and `'`. They should be escaped with single quotation mark `'`.~ See https://github.com/handsontable/hyperformula/issues/126#issuecomment-589553902

#### Non goals

- [x] Do not implement `scope`s. The only `scope` that is supported is the global one.
- [x] No additional options for named expressions.
- [x] No syntax support. Named Expressions are only available by the APIs.
- [x] No CRUD support. No named expression in formulas syntax = no CRUD. Easy.
- [x] No Copy&Paste support. Same as CRUD, nothing to copy & paste ATM.
