### ISSUE TITLE
Small fixes after the initial 0.1.0 release

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#420]
### Description

Looks like we've missed a spot here and there. Our friends are reporting various places we can improve on so I'm creating an Epic to track all the ideas and tasks. Fell free to add a comment or edit the list.

- [x] #419 Typo fix - calculateFormula 
- [x] ~#424 languages are not exported to NPM tgz~
- [x] #432 languages _were_ exported, but differently than expected - needed clarification in the docs
- [x] #428 Languages import problem. 
- [x] #421 fix typos and broken links in documentation: API, guides, README file
- [x] #426 Swap the demo urls from `0.1.0` to `0.1.x`
- [x] #427 Update the `yarn.lock` file
- [x] Add badges to README.md
- [ ] Add logo to Release Notes

* HyperFormula version: 0.1.0
* Browser Name and version: any
* Operating System: any

**Comment by jansiegel** [comment]
> * Add logo to Release Notes

Something like this? @wojciechczerniak @krzysztofspilka? https://gist.github.com/jansiegel/6cabf1513cc07e257db200580fd8e089

**Comment by wojciechczerniak** [comment]
> > * Add logo to Release Notes
> 
> Something like this? @wojciechczerniak @krzysztofspilka? https://gist.github.com/jansiegel/6cabf1513cc07e257db200580fd8e089

I don't want to be the guy who says it should be bigger 😄 

It got lost with the big text block next to it. Maybe a more visible banner? Or a screenshot from the video? @krzysztofspilka

**Comment by jansiegel** [comment]
I just taken the logo from the readme ¯\\\_(ツ)\_/¯

**Comment by wojciechczerniak** [comment]
Done and released
