### ISSUE TITLE
[v1.0.0] First Release

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#54]
Description

A checklist for the first release in January

- [ ] #61 Small Group Evaluator requirements
- [ ] Final package build
    - [x] #50 All package.json fields should be correctly filled in
    - [x] #49 Add ES, CommonJS, and UMD builds. Add all package types to package.json
    - [x] #83 Refactor main exports for use in UMD builds
    - [x] #19 Export version and build date as static properties
    - [x] #23 Benchmarks and R&D code from the software release
    - [x] #118 Remove moment.js dependancy
    - [x] #71 Support newer versions of node.js
    - [x] #142 Support NPM
    - [x] #123 Configure CI
    - [ ] Release process
        - [ ] Update dependencies (remove lock)
        - [ ] Change `version` in package.json
        - [ ] Set `buildDate` and `version`
        - [ ] Change `private` flag in package.json
        - [ ] Add `license` field in package.json
        - [ ] Check license banner in UMD build
        - [ ] Add Google Analytics to docs and API reference
    - [x] #219 Test runner for web browsers
    - [x] #222 Add LicenseKey verification
    - [ ] Performance benchmark
- [ ] Functionality
    - [ ] #231 Implement VERSION function
    - [x] #7 API
        - [x] #45 Add destroy method to clean up after engine instance
        - [x] #33 We need a way to clear all data from a worksheet
        - [x] #32 Worksheet helpers and name to id translation
        - [x] #74 Add support for copy/cut/paste
        - [x] #22 Address translation helpers
        - [x] #146 Add better config validation
        - [x] #178 Get all sheet data method
        - [x] #34 Range getters 
        - [x] #24 Add formula helpers: calculate, validate, normalize
        - [ ] #38 Support sort and filters integration
        - [x] #18 Finish batch operations API
        - [x] #122 Input and output types should be consistent
        - [x] #31 Cleanup set cell value methods
        - [x] #179 Add sheet self-references to fix copy/cut/paste limitation
        - [ ] #58 Global config settings
        - [x] #182 It's not possible to edit an invalid formula
        - [x] #207 It's not possible to add worksheet with references after engine initialization
        - [x] #29 Add move rows and columns operations
        - [x] #37 Add support to register custom formula / customize loaded ones
        - [x] #36 Add custom languages support
        - [x] #209 Undo/Redo support
        - [x] #135 Add support for events
    - [x] Syntax
        - [x] #70 Add support for "unary plus" operator
        - [x] #44 Support coercion of strings to number with % sign
        - [x] #12 Worksheet references and special characters in names
        - [x] #68 Keep the whitespace
        - [x] #129 Parse leading apostrophe to set the value as text
        - [x] #76 Support omitting optional function parameters
        - [x] #198 References (cell, range, sheet) are not fully supported
        - [x] #13 Built-in function required for the initial release
    - [ ] Data types
        - [ ] #229 time support, HH:mm, HH:mm:ss, AM/PM, duration
        - [x] #4 numeric operations precision
        - [x] #3 Support date type in arithmetic and comparison operators
        - [x] #130 string comparison operators are very naive, we need better support
        - [x] #177 Handle octal, binary, hexadecimal, and numeric separators
        - [x] #42 Add numeric separator as a configuration option
        - [x] #10 ISBLANK and null values
        - [x] #173 #142 BLANK should be coerced to 0 when used with operators
        - [x] #139 Support leap year 1900 in date type
        - [x] #176 Unsupported data types should report a meaningful error message
        - [x] #172 Operations that overflow integer with Infinity should report #NUM! error
        - [x] #119 Parse decimal without leading zero consistently
        - [x] #217 Distinct Logical type support
    - [x] Errors support
        - [x] #63 Constant errors support
        - [x] #48 CellError should return a localized error value
        - [x] #144 #145 Errors should be propagated correctly when used with operators
- [ ] #205 Documentation (part of it)
    - [ ] #8 Readme.md
    - [ ] #51 License.txt
    - [ ] #202 Improve API reference
    - [x] Describe all config options #58
    - [x] #125 Generate syntax diagram for grammar
    - [ ] #149 Add developer documentation
    - [x] #53 Code_of_Conduct.md
    - [x] #55 Changelog.md
    - [x] #52 Contributing.md and CLA
    - [x] #21 Create issue and PR templates
    - [ ] Examples for usage with Vue, React, Angular, TS
    - [ ] Demo with export/import external JSON
    - [ ] Example Custom Formula: called `=FOO()` will return `"bar"`
- [ ] https://github.com/handsontable/hyperformula/issues/54#issuecomment-590362748 Acceptance tests @aninde

**Comment by wojciechczerniak** [comment]
All the tasks required for initial release were done and successfully published 🎉
