### ISSUE TITLE
ODFF 1.3 Small Group Evaluator requirements

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#61]
### Description

The first milestone should be to meet ODFF 1.3 Small Group Evaluator requirements. This gives us an MVP as defined by the OpenFormula standard.

Most of those requirements are already met. Some of the functions are already on our list #13

### Requirements for Small Group Evaluator

From ODFF 1.3:

- [x] A) [3.7](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017874_715980110) It shall implement at least the limits defined in the “Basic Limits” section #59
- [ ] B) It shall implement the syntax defined in these sections on syntax: 
    - [x] [4.11.11](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017928_715980110) Criteria 
    - [x] [5.2](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017934_715980110) Basic Expressions #76
    - [x] [5.3](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017936_715980110) Constant Numbers 
    - [x] [5.4](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017938_715980110) Constant Strings 
    - [x] [5.5](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017940_715980110) Operators 
        - [x] Prefix "-" has higher precedence than "^"
        - [ ] Reference intersection has a higher precedence than reference union
        - [x] Precedence can be overridden by using parentheses
        - [x] "Unnecessary" parentheses and white space should be retained, people add them to improve readability.
    - [x] [5.6](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017942_715980110) Functions and Function Parameters 
        - [x] Function names are case-insensitive ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/parser/parser.spec.ts#L218-L223))
        - [x] Functions can be called wit 0 parameters i.e. `=TRUE()` ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/parser/parser.spec.ts#L86-L92))
        - [x] Parameters are separated using the semicolon `;` ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/parser/parser.spec.ts#L225-L235))
        - [x] Supports naming as defined by [XML letter, digit and combiningChar](https://www.w3.org/TR/2006/REC-xml-20060816/#NT-Letter)
    - [x] [5.7](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017944_715980110) Nonstandard Function Names ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/parser/parser.spec.ts#L102-L108))
        - [x] Not supported function should compute as an Error other than `#N/A`
        - [x] Functions that are not part of the ODFF spec should be namespaced if possible 
    - [ ] [5.8](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017946_715980110) References #64 #65 #66
    - [x] [5.11](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017964_715980110) Simple Named Expressions
    - [x] [5.12](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017966_715980110) Constant Errors #63
    - [x] [5.14](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017970_715980110) Whitespace #68
        - [x] Ignore the whitespace in calculations
        - [x] Support four whitespace types: SPACE (U+0020), CHARACTER TABULATION (U+0009), LINE FEED (U+000A), CARRIAGE RETURN (U+000D)
        - [x] Retain whitespace entered by the user for formatting purposes
- [x] C) It shall implement all implicit conversions for the types it implements, at least 
    - [x] [6.3.2](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017982_715980110) Conversion to Scalar
    - [x] [6.3.5](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017988_715980110) Conversion to Number 
        - [x] Number, return as is
        - [x] Logical, return 0 if FALSE, and 1 if TRUE
        - [x] Text
        - [x] Reference ... 😱 
    - [x] [6.3.12](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018002_715980110) Conversion to Logical 
        - [x] Number is TRUE for `<>0` and FALSE for `0`
        - [x] Depends on implementation
            - [x] Return always FALSE
            - [x] Return always Error
            - [x] Convert "false" (ignore case) to FALSE, "true" to TRUE. Fallback to FALSE or return an Error if conversion failed. Locale specific, use "prawda" for pl-PL etc.
        - [x] Logical as is
        - [x] Reference, convert to scalar first. Empty cell is FALSE.
    - [x] [6.3.14](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018004_715980110) Conversion to Text
        - [x] Number is transformed to Text with no whitespace
        - [x] Text is returned as is
        - [x] Logical returns "TRUE" and "FALSE" as uppercase strings
        - [x] Reference: conversion to scalar. If empty, return empty string. (fails on range)
    - [x] Reference 
    - [x] and when an expression returns an Error
- [ ] D) It shall implement the following operators (which are all the operators except reference union (~)): 
    - [x] [6.4.9](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018028_715980110) Infix Operator Ordered Comparison ("<", "<=", ">", ">=")  ([spec](https://github.com/handsontable/hyperformula/blob/master/test/interpreter/boolean-operators.spec.ts))
    - [x] [6.4.10](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018030_715980110) Infix Operator "&” ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-concatenate.spec.ts))
    - [x] [6.4.2](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018014_715980110) Infix Operator "+” ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-plus.spec.ts))
    - [x] [6.4.3](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018016_715980110) Infix Operator "-” ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-minus.spec.ts))
    - [x] [6.4.4](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018018_715980110) Infix Operator "*” ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-times.spec.ts))
    - [x] [6.4.5](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018020_715980110) Infix Operator "/” ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-division.spec.ts))
    - [x] [6.4.6](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018022_715980110) Infix Operator "^” ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-power.spec.ts))
    - [x] [6.4.7](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018024_715980110) Infix Operator "=” ([spec](https://github.com/handsontable/hyperformula/blob/master/test/interpreter/boolean-operators.spec.ts))
    - [x] [6.4.8](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018026_715980110) Infix Operator "<>” ([spec](https://github.com/handsontable/hyperformula/blob/master/test/interpreter/boolean-operators.spec.ts))
    - [x] [6.4.14](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018038_715980110) Postfix Operator “%” #44 ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-percent.spec.ts))
    - [x] [6.4.15](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018040_715980110) Prefix Operator “+” #70 (~spec~)
    - [x] [6.4.16](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018042_715980110) Prefix Operator “-” ([spec](https://github.com/handsontable/hyperformula/blob/b3752ae004ad4e7402ea5403b98660b3458d1918/test/interpreter/operator-unary-minus.spec.ts))
    - [ ] [6.4.12](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018034_715980110) Infix Operator Reference Intersection ("!") #15 (~spec~)
    - [ ] [6.4.11](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018032_715980110) Infix Operator Range (":") #15 (~spec~)
- [ ] E) ~It shall implement at least the following functions as defined in this specification~ Extracted to separate issue, will be tracked here #274
- [x] F) It need not evaluate references that contain more than one area. 
- [x] G) It need not implement
    - [x] inline arrays 5.13
    - [x] complex numbers 4.4
    - [x] and the reference union operator 6.4.13

### Reference
https://www.oasis-open.org/committees/documents.php?wg_abbrev=office
