### ISSUE TITLE
Public API proposal

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#7]
### Description
A proposal for a public API. It will be easier to discuss it here.

### Requirements

- Sheets are sometimes used as a number, sometimes as a string. This should be unified.
- addSheet` method should not generate an ID. Instead, it should accept a name as an argument. This way we can name it the same as Handsontable instance and use this for multiple worksheets support.
- Add general-purpose and lifecycle methods: `destroy`, `updateConfig` 
- Add better formula support: `registerFormula`, `getFormula`, `listAllFormulas`
- Add better language support: `registerLanguage`, `getLanguage`, `listAllLanguages`
- Add helpers for formulas: `calculateFormula`, `validateFormula`, `normalizeFormula`
- Add value accesors: `getCellValue`, `getCellFormula`, `getRangeValues`, `getRangeFormulas`
- Add helpers for address translations
- Add events to notify about graph / value changes: `valueUpdated`, `formulaUpdated`
- Remove methods that are unnecessary as a public API: `getSheetDimensions`, `getSheetsDimensions`, `getStats`, `forceApplyPostponedTransformations`, `disableNumericMatrices`, `getSheetsDimensions`, `getSheetDimensions`
- `isItPossibleToChangeContent` is a neat idea, but it will work only for a single cell in cooperation with `setCellContent`. How do we validate if we can proceed with `setMultipleCellContents` ?
- Export all enums, types and errors as statics so they are availble for developers
- API methods `addColumns` and `removeColumns` have inconsistent signatures. Same for `addRow`, `removeRow`, `isItPossibleToAddColumns`, `isItPossibleToAddColumns`.

#### API for V1
- [x] Constructor
    ```ts
    public static buildFromSheets(sheets: Sheets, config?: Config): HyperFormula;
    public static buildFromArray(sheet: Sheet, config?: Config): HyperFormula;
    public static buildEmpty(config?: Config): HyperFormula;

    public constructor(config?: Config): HyperFormula;
    ```

- [x] Destroy instance #45
    ```ts
    public destroy(): void;
    ```

- [x] Sheet operations #26 / #28
    ```ts
    public addSheet(name: string): string;
    public removeSheet(name: string);
    public isItPossibleToAddSheet(name: string): boolean;
    public isItPossibleToRemoveSheet(name: string): boolean;
    ```

- [x] Sheet helpers #32
    ```ts
    public sheetId(sheetName: string): number | undefined;
    public sheetName(sheetId: number): string | undefined;
    public doesSheetExist(sheetName: string): boolean;
    public numberOfSheets(): number;
    public renameSheet(sheetId: number, newName: string): void;
    ```

- [x] Cell getters
    ```ts
    public getCellValue(address: SimpleCellAddress): CellValue; 
    public getCellFormula(address: SimpleCellAddress): CellFormula;
    public getCellSerialized(address: SimpleCellAddress): CellValue;
    ```

- [x] Cells value setters #31
    ```ts
    public setCellsContents(cellAddress: SimpleCellAddress, values: CellValue[][]): CellValueChange[];
    public isItPossibleSetCellContents(cellAddress: SimpleCellAddress, width = 1, height = 1): boolean;
    ```

- [x] Sheet set content #33
    ```ts
    public isItPossibleToSetSheetContent(sheet: string): boolean;
    public setSheetContent(sheet: string, values: CellValue[][]): CellValueChange[];
    ```

- [x] Cell helpers #30
    ```ts
    public getCellType(address: SimpleCellAddress): CellType
    public doesCellHaveSimpleValue(address: SimpleCellAddress): boolean 
    public doesCellHaveFormula(address: SimpleCellAddress): boolean
    public isCellEmpty(address: SimpleCellAddress): boolean 
    public isCellPartOfMatrix(address: SimpleCellAddress): boolean 
    public getCellValueType(address: SimpleCellAddress): CellValueType
    ```

- [x] Create / remove row / column with noncontigous support #29
    ```ts
    type Index  = [number, number] // [startIndex, amount]

    public addRows(sheet: number, ...indexes: Index[]): CellValueChange[]
    public removeRows(sheet: number, ...indexes: Index[]): CellValueChange[]
    public addColumns(sheet: number, ...indexes: Index[]): CellValueChange[]
    public removeColumns(sheet: number, ...indexes: Index[]): CellValueChange[]

    public isItPossibleToAddRows(sheet: number, ...indexes: Index[]): CellValueChange[]
    public isItPossibleToRemoveRows(sheet: number, ...indexes: Index[]): CellValueChange[]
    public isItPossibleToAddColumns(sheet: number, ...indexes: Index[]): CellValueChange[]
    public isItPossibleToRemoveColumns(sheet: number, ...indexes: Index[]): CellValueChange[]
    ```

- [x] Address translation helpers #22
    ```ts
    public simpleCellAddressToString(address: SimpleCellAddress, sheet: number): string
    public simpleCellAddressFromString(stringAddress: string, sheet: number): SimpleCellAddress
    ```

- [x] Batch operations #18
    ```ts
    public suspendEvaluation(): void
    public resumeEvaluation(): void
    public isEvaluationSuspended(): boolean
    public batch(callback: function): CellValueChange[]
    public rebuildAndRecalculate(): void
    ```

- [x] Export `version` and `buildDate` from `package.json` #19
    ```ts
    static version: string; // semver
    static buildDate: string;
    ```

- [x] moveRows / moveColumns / moveSheets methods #29
    ```ts
    public moveRows(sheet: number, ... ? ...): CellValueChange[]
    public isItPossibleToMoveRows(sheet: number, ... ? ...): CellValueChange[]

    public moveColumns(sheet: number, ... ? ...): CellValueChange[]
    public isItPossibleToMoveColumns(sheet: number, ... ? ...): CellValueChange[]
    ```

- [x] Formulas helpers #24
   ```ts
    public calculateFormula(formula: string): any;
    public validateFormula(formula: string): boolean; 
    public normalizeFormula(formula: string): string;
    ```

- [x] Events #135 
    ```ts
    public on(eventName: string | enum, callback): void;
    public once(eventName: string | enum, callback): void;
    public off(eventName: string | enum, callback): void;
    ```

- [x] Named Expressions #239
   ```ts
    public addNamedExpression(name: string, value, scope, { comment, visibility })
    public removeNamedExpression(name: string, scope: string)
    public updateNamedExpression(name: string, value, scope, { comment, visibility })
    public getNamedExpressionValue(name string, scope: string)
    public getNamedExpressionFormula(name: string, scope: string)
    public listAllNamedExpressions(scope?: string)
   ```

- [x] Get all sheet data #178 
    ```ts
   public getAllSheetsFormulas(): Record<string, Maybe<string>[][]>
   public getAllSheetsValues(): Record<string, CellValue[][]>
   public getAllSheetsSerialized(): Record<string, CellValue[][]>

   public getSheetSerialized(sheet: number): CellValue[][]
   public getSheetFormulas(sheet: number): Maybe<string>[][]
   public getSheetValues(sheet: number): CellValue[][]
   ```

- [x] Range getters #34
    ```ts
    public getRangeValues(range: AbsoluteCellRange): CellValue[][]
    public getRangeFormulas(range: AbsoluteCellRange): CellValue[][]
    public getRangeSerialized(range: AbsoluteCellRange): CellValue[][]
    ```

- [x] Update configuration #117
    ```ts
    public updateConfig(config: ConfigParams): void
    public getConfig(): ConfigParams
    ```

- [ ] Custom formulas API #37 
    ```ts
    public static registerFormula(formula: Formula): void
    public static getFormulas(): string[]
    ```

- [x] Custom languages API #36 
    ```ts
    public static registerLanguage(code: string, lang: RawTranslationPackage): void
    public static getLanguages(code: string): TranslationPackage
    public static getRegisteredLanguagesCodes(): string[]
    public static unregisterLanguage(code: string): void
    ```
