### ISSUE TITLE
NCBR: add acknowledgments to milestones and update current ones

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#724]
- [x] Update ack in docs
- [x] Update ack for `develop` branch
- [x] Update ack for `milestone-4` branch
- [x] Add ack to `milestone-3` branch
- [x] Add ack to `milestone-2` branch
- [x] Add ack to `milestone-1` branch

**Comment by wojciechczerniak** [comment]
Bonus:
- [ ] Add ack to `milestone-2-old-way` branch
